---
  ansible_host: 192.168.1.103
  ansible_user: admin
  ansible_ssh_pass: admin
  ansible_connection: network_cli
  ansible_network_os: nxos
  ansible_become: yes
  ansible_become_method: enable
  ansible_become_password: admin
