---
  ansible_user: admin
  ansible_ssh_pass: admin
  ansible_connection: network_cli
  ansible_network_os: nxos
  ansible_become: yes
  ansible_become_method: enable
  ansible_become_password: admin
  ntp_servers:
   - 172.20.1.1
   - 172.20.2.1
